#!/usr/bin/env python

import os
import yaml
import logging

import h5py
import numpy as np

import bluepy

from psp_validation import psp
from psp_validation.pathways import get_pairs
from psp_validation.persistencyutils import dump_raw_traces_to_HDF5


LOGGER = logging.getLogger(__name__)


def load_config(filepath):
    """ Load YAML b config. """
    title = os.path.splitext(os.path.basename(filepath))[0]
    with open(filepath, 'r') as f:
        config = yaml.load(f)
    return title, config


def get_traces(blue_config, pre_gid, post_gid, protocol, n_repetitions, seed):
    from psp_validation.psp import run_pair_trace_simulations

    hold_V = protocol['hold_V']
    if hold_V is None:
        hold_I = None
    else:
        from bglibpy import holding_current
        LOGGER.info("Calculating a%d holding current", post_gid)
        hold_I, _ = holding_current(hold_V, post_gid, blue_config)

    LOGGER.info("Running simulation(s) for a%d -> a%d pair (base_seed=%d)", pre_gid, post_gid, seed)
    return run_pair_trace_simulations(
        blue_config=blue_config,
        pre_gid=pre_gid,
        post_gid=post_gid,
        hold_I=hold_I,
        hold_V=hold_V,
        t_stim=protocol['t_stim'],
        t_stop=protocol['t_stop'],
        g_factor=1.0,
        record_dt=protocol['record_dt'],
        post_ttx=protocol['post_ttx'],
        v_clamp=protocol['v_clamp'],
        spikes=None,
        repetitions=n_repetitions,
        rndm_seed=seed,
        use_multiprocessing=True
    )


def main(args):
    logging.basicConfig(level=logging.WARNING)
    LOGGER.setLevel({
        0: logging.WARNING,
        1: logging.INFO,
        2: logging.DEBUG
    }[args.verbose])

    if args.seed is None:
        seed = np.random.randint(1e9)
    else:
        seed = args.seed

    np.random.seed(seed)

    circuit = bluepy.Circuit(args.circuit).v2

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    for config_path in args.task_config:
        title, config = load_config(config_path)
        LOGGER.info("Processing '%s' task...", title)

        pathway = config['pathway']
        if isinstance(pathway, list):
            for item in pathway:
                assert isinstance(item, list) and len(item) == 2
            pairs = pathway
        else:
            LOGGER.info("Querying pathway pairs...")
            pairs = get_pairs(circuit, **pathway)

        protocol = config['protocol']
        n_repetitions = config['n_repetitions']

        t_stim = config['protocol']['t_stim']
        t_start = t_stim - 10.
        spike_filter = psp.default_spike_filter(t_start)

        all_traces = []
        all_amplitudes = []
        for pre_gid, post_gid in pairs:
            traces = get_traces(args.circuit, pre_gid, post_gid, protocol, n_repetitions, seed=seed)
            syn_type = psp.synapse_type(args.circuit, pre_gid)
            vts = np.array([tr[:2] for tr in traces])
            v_mean, t, _, _ = psp.mean_pair_voltage_from_traces(vts, spike_filter)
            ampl = psp.get_peak_amplitude(t, v_mean, t_start, t_stim, syn_type)
            all_amplitudes.append(ampl)
            if args.dump_traces:
                all_traces.append(traces)

        output_path = os.path.join(args.output_dir, title + "_amplitudes.csv")
        np.savetxt(output_path, all_amplitudes, fmt="%.9f")

        if args.dump_traces:
            traces_path = os.path.join(args.output_dir, title + "_traces.h5")
            with h5py.File(traces_path, 'w') as h5f:
                dump_raw_traces_to_HDF5(h5f, title, all_traces)


if __name__ == "__main__" :
    import argparse
    parser = argparse.ArgumentParser(description="Obtain PSP amplitudes")
    parser.add_argument(
        "-c", "--circuit",
        required=True,
        help="Path to BlueConfig"
    )
    parser.add_argument(
        "-o", "--output-dir",
        required=True,
        help="Path to output folder"
    )
    parser.add_argument(
        "--dump-traces",
        action="store_true",
        help="Dump PSP traces"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Pseudo-random generator seed"
    )
    parser.add_argument(
        "-v", "--verbose",
        action="count",
        default=0,
        help="-v for INFO, -vv for DEBUG"
    )
    parser.add_argument(
        "task_config",
        nargs="*",
        help="YAML task config(s)"
    )
    main(parser.parse_args())
